name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

    - name: Lint Python code with flake8
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint Dockerfile using Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: app/Dockerfile

    - name: Run tests with pytest and check coverage
      env:
        PYTHONPATH: app
      run: |
        pytest --cov=app --cov-report=term-missing --cov-report=html:coverage_report

    - name: Upload coverage report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: coverage_report/

  deploy:
    needs: lint-and-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: true

    - name: Deploy application via Docker Compose
      run: |
        cd ~/lab2
        docker compose down --volumes --remove-orphans
        docker compose up --build -d

    - name: Verify deployment status
      run: |
        echo "Waiting 20 seconds for containers to fully start..."
        sleep 20
        
        STATUS_TASKS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost/tasks)
        echo "Backend responded with status: $STATUS_TASKS"
        
        if [ "$STATUS_TASKS" -eq 200 ] || [ "$STATUS_TASKS" -eq 201 ] || [ "$STATUS_TASKS" -eq 500 ]; then
          echo "Verification Success! Nginx successfully routes requests to backend."
        else
          echo "Verification Failed! Got status $STATUS_TASKS"
          exit 1
        fi
